{"name": "test_demo", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "@pytest.mark.usefixtures(\"class_demo\")\n    @pytest.mark.usefixtures(\"function_demo\")\n    @pytest.mark.demo\n    def test_demo():\n        print(\"HHHHHHHHHHHHHHHHHHHHHH\")\n>       assert False\nE       assert False\n\nTestCases\\test_login.py:16: AssertionError"}, "start": 1591634192847, "stop": 1591634192847, "uuid": "74b5fc98-6a51-4af4-818b-ca1f942c35d0", "historyId": "98d2df8f2fcff07acce8978d80e87a6c", "testCaseId": "3205837d706d91ea3610c466894b29d0", "fullName": "TestCases.test_login#test_demo", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('function_demo')"}, {"name": "tag", "value": "demo"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "DESKTOP-7K6BCD4"}, {"name": "thread", "value": "65272-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}